Product.create!(name: "Broom", price: 8.00, description: "This is a broom. Does it really need a description?", supplier_id: 2, quantity: 100)
Product.create!(name: "Dustpan", price: 4.00, description: "This is a dustpan. It picks up dust", supplier_id: 2, quantity: 500)
Product.create!(name: "Vacuum", price: 35.00, description: "This is a vacuum. It cleans stuff.", supplier_id: 1, quantity: 25)
Product.create!(name: "Soapbar", price: 2.00, description: "This is a bar of soap. Use it when you're smelly.", supplier_id: 3, quantity: 1000)
Supplier.create!({ name: "Costco", email: "costco@costco.com", phone_number: "(800)123-4567" })
Supplier.create!({ name: "Wal-Mart", email: "wal-mart@walmart.com", phone_number: "(123)456-7890" })
Supplier.create!({ name: "Target", email: "target@target.com", phone_number: "(098)765-4321" })
Image.create!({ url: "https://www.bissell.com/dw/image/v2/BDKV_PRD/on/demandware.static/-/Sites-master-catalog-bissell/default/dw798d98da/hi-res/Product-Images/3536/3536_CleanView_2.0_Secondary1.png?sw=575&sh=575&sm=fit", product_id: 3 })
Image.create!({ url: "https://www.bissell.com/dw/image/v2/BDKV_PRD/on/demandware.static/-/Sites-master-catalog-bissell/default/dwb99b8d59/hi-res/Product-Images/3536/3536_CleanView_2.0_Secondary4.jpg?sw=575&sh=575&sm=fit", product_id: 3 })
Image.create!({ url: "https://www.bissell.com/dw/image/v2/BDKV_PRD/on/demandware.static/-/Sites-master-catalog-bissell/default/dw74552d4b/hi-res/Product-Images/3536/3536_CleanView_2.0_Secondary7.jpg?sw=575&sh=575&sm=fit", product_id: 3 })
Image.create!({ url: "https://s.turbifycdn.com/aah/1877floorguy/libman-wide-commercial-angle-broom-15-45.png", product_id: 1 })
Image.create!({ url: "https://www.gordonbrush.com/productphotos/12-metal-dustpan-m445140-2035.jpg", product_id: 2 })
Image.create!({ url: "https://predeprovence.com/cdn/shop/products/Linden.jpg?v=1576877804", product_id: 4 })
Image.create!({ url: "https://predeprovence.com/cdn/shop/products/71DwAo-rsAL._SX679.jpg?v=1677285369", product_id: 4 })
Image.create!({ url: "https://predeprovence.com/cdn/shop/products/7109REUri-L._SX679.jpg?v=1677285369", product_id: 4 })
Image.create!({ url: "https://predeprovence.com/cdn/shop/files/612082761818_01.jpg?v=1696019378", product_id: 4 })
Category.create!(name: "Cleaning Supplies")
Category.create!(name: "Electronics")
Category.create!(name: "Soap")
CategoryProduct.create!(product_id: 1, category_id: 1)
CategoryProduct.create!(product_id: 2, category_id: 1)
CategoryProduct.create!(product_id: 3, category_id: 1)
CategoryProduct.create!(product_id: 4, category_id: 1)
CategoryProduct.create!(product_id: 3, category_id: 2)
CategoryProduct.create!(product_id: 4, category_id: 3)
